<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__keyword</name>
   <tag></tag>
   <elementGuidId>b2f12a50-66a9-47cd-b1f1-aebba2eea3b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='keyword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;keyword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcc37076-98c1-4321-887a-406708161490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>64fc2166-85bb-4731-be77-9faf7f55f918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>79844118-1d05-4bb1-8cd5-043df4fe6f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84cfc7ff-92b1-40cf-90ba-18fb8d13437a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchContent&quot;)/form[1]/input[1]</value>
      <webElementGuid>7ac5d99d-6aa0-4f8b-a837-6c64c1e9e4f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='keyword']</value>
      <webElementGuid>c40f06f3-3c7a-4cdd-9db3-e797373804e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchContent']/form/input</value>
      <webElementGuid>e8a18d01-5f8f-4e83-aaff-6a00dbfadd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>29854147-3e5e-4010-b11a-d6ef9f82546a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'keyword' and @type = 'text']</value>
      <webElementGuid>128f8bce-dded-442f-9193-f55e4939c58b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
